source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SSCacheControl_Example', :exclusive => true do
  pod "SSCacheControl", :path => "../"
end

target 'SSCacheControl_Tests', :exclusive => true do
  pod "SSCacheControl", :path => "../"

  
end
